# routes/__init__.py
from . import auth
from . import clients
from . import projects
from . import invoices
from . import leads
from . import proposals
from . import campaigns
from . import targets
from . import sales_kits
from . import briefs
from . import productions
from . import publishing
from . import reviews
from . import seo
from . import network
from . import competitors
from . import dashboard
from . import ai